#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS

#define INITIAL_PROMPT "*Welcome to Spooks bank!\nWho are you?\n1. Admin\t2. Customer\nPress any other number to exit\nEnter the number corresponding to the choice!"


// ========== COMMON TEXT =============================

// LOGIN
#define LOGIN_ID "&Enter your login ID:\n"
#define PASSWORD "&Enter your password:\n"
#define INVALID_LOGIN "*The login ID specified doesn't exist!$\n"
#define INVALID_PASSWORD "*The password specified doesn't match!$"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "&Enter the account number of the account you're searching for"
#define GET_CUSTOMER_ID "&Enter the customer ID of the customer you're searching for"

#define ERRON_INPUT_FOR_NUMBER "*It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "*It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "*No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "*No customer could be found for the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "*No account could be found for the given account number\n"

#define TRANSACTIONS_NOT_FOUND "*No transactions were performed on this account by the customer!\n"

// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "*Welcome dear admin! With great power comes great responsibility!\nEnter your credentials to unlock this power!"
#define ADMIN_LOGIN_SUCCESS "sucess\n"

// ADMIN MENU
#define ADMIN_MENU "&Welcome superman!\n1.Add new employee\n2. Modify employee details\n3.Get employee details\n4.Manage user roles \n Enter your choice : \n"

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_PRIMARY "&Enter the details for the primary customer\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "&Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "&What is the customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "&What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "&What is the customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "*The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "spookytime" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "*The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "*It seems you've entered a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD ACCOUNT

#define ADMIN_ADD_ACCOUNT_NUMBER "*The newly created account's number is :"

// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "&What is the account number of the account you want to delete?"
#define ADMIN_DEL_ACCOUNT_SUCCESS "*This account has been successfully deleted\nRedirecting you to the main menu ...^"
#define ADMIN_DEL_ACCOUNT_FAILURE "*This account cannot be deleted since it still has some money\nRedirecting you to the main menu ...^"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "&Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "&Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "&What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "&What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "&What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "*The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "*Logging you out now superman! Good bye!$"
#define NO_TRANSACTIONS "*No transactions were found"
// ====================================================
// ========== LOAN SPECIFIC TEXT ====================

#define LOAN_AMOUNT_PROMPT "&Enter the amount you wish to apply for the loan: "
#define LOAN_PURPOSE_PROMPT "&Enter the purpose for the loan: "
#define LOAN_APPLICATION_SUCCESS "*Loan application submitted successfully! Your application ID is: "
#define LOAN_APPLICATION_FAILURE "*Error applying for loan. Please try again later."
#define LOAN_AMOUNT_INVALID "*Invalid loan amount specified. Please try again."

// ====================================================

// ========== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "*Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_PROMPT_ID "&Please enter your login ID:\n"
#define CUSTOMER_LOGIN_PROMPT_PASSWORD "&Please enter your password:\n"
#define CUSTOMER_LOGIN_FAILED "*Login failed. Invalid ID or password.\n"
#define CUSTOMER_LOGIN_SUCCESS "*Login successful! Welcome."

#define CUSTOMER_ID_DOES_NOT_EXIST "*Customer ID does not exist!\n"
#define ACCOUNT_INACTIVE "*Account is inactive.\n"

#define CUSTOMER_LOGOUT "*Logging you out now dear customer! Good bye!$"

// ADMIN MENU
#define CUSTOMER_MENU "& Login Sucess \n1. Transaction History\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\n7.Feedback\n8. Apply for Loan\n9. Logout\nEnter the choice\n"
#define WRONG_CHOICE "*INVALID CHOICE"
#define ACCOUNT_DEACTIVATED "*It seems your account has been deactivated!\n"

#define DEPOSIT_AMOUNT "&How much is it that you want to add into your bank?\n"
#define DEPOSIT_AMOUNT_INVALID "*You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "*The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT "&How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "*You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "*The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "&Enter your old password\n"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "*The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "&Enter the new password\n"
#define PASSWORD_CHANGE_NEW_PASS_RE "&Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "*The new password and the reentered passwords don't seem to pass!^\n"
#define PASSWORD_CHANGE_SUCCESS "*Password successfully changed!\n"

// ====================================================
// ========== FEEDBACK SPECIFIC TEXT ====================

#define FEEDBACK_PROMPT "&Please enter your feedback (max 500 characters): "
#define FEEDBACK_SUCCESS "*Thank you for your feedback! Your feedback has been recorded."
#define FEEDBACK_FAILURE "*Error submitting feedback. Please try again later."
#define FEEDBACK_TOO_LONG "*Your feedback exceeds the allowed 500 characters. Please shorten your feedback."

// Feedback file for storing feedbacks
//#define FEEDBACK_FILE "../Banking/FEEDBACK_FILE"
#define CUSTOMER_FILE "/home/tushar/Banking/CUSTOMER_FILE"
#define EMPLOYEE_FILE "/home/tushar/Banking/EMPLOYEE_FILE"
#define LOAN_FILE "/home/tushar/Banking/LOAN_FILE"
#define ACCOUNT_FILE "/home/tushar/Banking/ACCOUNT_FILE"
#define FEEDBACK_FILE "/home/tushar/Banking/FEEDBACK_file"
#define TRANSACTION_FILE "/home/tushar/Banking/TRANSACTION_FILE"
// ========== LOGOUT AND EXIT TEXT ===================

#define ADMIN_LOGOUT "*Logging you out now superman! Good bye!$"
#define CUSTOMER_LOGOUT "*Logging you out now dear customer! Good bye!$"
#define EXIT_MESSAGE "*The system is shutting down. Goodbye!$"

// ====================================================

// Messages for customer management
#define ADD_NEW_CUSTOMER_SUCCESS "*New customer added successfully.\n"
#define ADD_NEW_CUSTOMER_FAILURE "*Failed to add new customer.\n"
#define MODIFY_CUSTOMER_SUCCESS "*Customer details modified successfully.\n"
#define MODIFY_CUSTOMER_FAILURE "*Failed to modify customer details.\n"
#define LOAN_APPLICATION_RECEIVED "*Loan application received successfully.\n"
#define LOAN_APPLICATION_FAILED "*Failed to process loan application.\n"
#define LOAN_APPROVED "*Loan application approved successfully.\n"
#define LOAN_REJECTED "*Loan application rejected successfully.\n"
#define VIEW_LOAN_APPLICATIONS "*Here are your assigned loan applications:\n"
#define NO_LOAN_APPLICATIONS "*No loan applications available.\n"

//======================================================================================================

// ========== MANAGER SPECIFIC TEXT ====================

// MANAGER LOGIN WELCOME
//#define MANAGER_LOGIN_WELCOME "*Welcome dear manager! Enter your credentials to access the management panel!"
#define MANAGER_LOGIN_SUCCESS "*Welcome manager!"

// MANAGER MENU
#define MANAGER_MENU "&Welcome manager! \n1. Activate Customer Account\n2. Assign Loan Applications\n3. Review Customer Feedback\n4. Change Password\n5. Deactivate Customer Account\n6. Logout\nEnetr the choice\n"

// ACTIVATE/DEACTIVATE CUSTOMER ACCOUNT
#define MANAGER_ACTIVATE_ACCOUNT_PROMPT "&Enter the account number of the customer to activate:"
#define MANAGER_DEACTIVATE_ACCOUNT_PROMPT "&Enter the account number of the customer to deactivate:"
#define MANAGER_ACTIVATE_SUCCESS "*The customer account has been successfully activated."
#define MANAGER_DEACTIVATE_SUCCESS "*The customer account has been successfully deactivated."
#define MANAGER_ACTIVATE_DEACTIVATE_FAILURE "*Failed to change the account status. Please try again."
#define ACCOUNT_ALREADY_DEACTIVATED "*Account is already deactivated.\n"

// ASSIGN LOAN APPLICATIONS
#define MANAGER_ASSIGN_LOAN_PROMPT "&Enter the employee ID to assign the loan application to:"
#define MANAGER_ASSIGN_LOAN_SUCCESS "*Loan application has been successfully assigned."
#define MANAGER_ASSIGN_LOAN_FAILURE "*Failed to assign loan application. Please try again."

// REVIEW FEEDBACK
#define MANAGER_REVIEW_FEEDBACK_PROMPT "*Here are the latest customer feedbacks:"
#define NO_FEEDBACKS_AVAILABLE "*No feedbacks are available at the moment."
#define INSUFFICIENT_FUNDS "*Not fund enough."
#define ACCOUNT_DETAILS_ERROR "*WRONG DETAILS.\n"
#define MAX_EMPLOYEES  30
#define MANAGER_LOGOUT  "LOGGING OUT"
#define LOGIN_ATTEMPT_EXCEEDED "MAXIMUM  LOGIN ATTEMPTS EXCEEDED"
#define MAX_LOGIN_ATTEMPTS 10


#endif
